Improve TikTok downloader

diff --git a/worker/tiktok-dl b/worker/tiktok-dl
--- a/worker/tiktok-dl
+++ b/worker/tiktok-dl
@@ -1,42 +1,80 @@
 #!/bin/bash
 
+YT_DLP="yt-dlp"
+
+SERVICE="TikTok"
+ID_FIELD="id"
+TITLE_FIELD="title"
+TIMESTAMP_FIELD="timestamp"
+UPLOADER_FIELD="uploader"
+
 download_tiktok_video () {
-    local INFO_JSON=$(yt-dlp -j "$1" 2>/dev/null)
-    # Variable is empty
-    if [[ -z "${INFO_JSON}" ]]; then
-        echo "error: unable to get info for '$1'" >&2
-        echo "running 'yt-dlp -F $1'"
-        yt-dlp -F "$1"
+    local temp_dir
+    temp_dir="$(mktemp -d -t tiktok_dl.XXXXXX -u)"
+    if ! mkdir -v "$temp_dir"; then
+        printf 'error: unable to create temporary directory: %s\n' "$temp_dir"
+        exit 1
+    fi
+
+    # yt-dlp adds the `.info.json` suffix automatically, so we use the base
+    # value below when setting the output path, and use `temp_info_json`
+    # everywhere else.
+    local temp_info_json_base
+    temp_info_json_base="$(mktemp -t info_json.XXXXXX -p "$temp_dir" -u)"
+    local temp_info_json
+    temp_info_json="$temp_info_json_base.info.json"
+
+    if ! cd "$temp_dir"; then
+        echo "error: cd '$temp_dir' failed" >&2
         return 1
     fi
-    local ID=$(echo $INFO_JSON | jq -r .id)
-    if [[ -z "${ID}" ]]; then
+
+    "$YT_DLP" --skip-download --write-info-json --write-pages --output "infojson:$temp_info_json_base" --newline --verbose "$1"
+
+    # File exists and is not empty
+    if [[ ! -s "$temp_info_json" ]]; then
+        echo "error: unable to get info for '$1'" >&2
+        return 1
+    fi
+
+    local ID
+    ID="$(jq -r ".$ID_FIELD" "$temp_info_json")"
+    if [[ -z "$ID" ]]; then
         echo "error: unable to get ID for '$1'" >&2
         return 1
     fi
-    local TITLE=$(echo $INFO_JSON | jq -r .title)
-    if [[ -z "${TITLE}" ]]; then
+
+    local TITLE
+    TITLE="$(jq -r ".$TITLE_FIELD" "$temp_info_json")"
+    if [[ -z "$TITLE" ]]; then
         echo "error: unable to get title for '$1'" >&2
         return 1
     fi
-    local TIMESTAMP=$(echo $INFO_JSON | jq -r .timestamp)
-    if [[ -z "${TIMESTAMP}" ]]; then
+
+    local TIMESTAMP
+    TIMESTAMP="$(jq -r ".$TIMESTAMP_FIELD" "$temp_info_json")"
+    if [[ -z "$TIMESTAMP" ]]; then
         echo "error: unable to get timestamp for '$1'" >&2
         return 1
     fi
-    local UPLOADER=$(echo $INFO_JSON | jq -r .uploader)
-    if [[ -z "${UPLOADER}" ]]; then
+
+    local UPLOADER
+    UPLOADER="$(jq -r ".$UPLOADER_FIELD" "$temp_info_json")"
+    if [[ -z "$UPLOADER" ]]; then
         echo "error: unable to get uploader for '$1'" >&2
         return 1
     fi
 
-    if [[ ! -d "/media/TikTok/@$UPLOADER" ]]; then
-        if ! mkdir -v "/media/TikTok/@$UPLOADER"; then
+    if [[ ! -d "/media/$SERVICE/@$UPLOADER" ]]; then
+        if ! mkdir -v "/media/$SERVICE/@$UPLOADER"; then
             exit 1
         fi
     fi
 
-    cd "/media/TikTok/@$UPLOADER"
+    if ! cd "/media/$SERVICE/@$UPLOADER"; then
+        printf 'error: failure changing to directory: %s\n' "/media/$SERVICE/@$UPLOADER" >&2
+        exit 1
+    fi
 
     local DIRECTORY="$ID"
 
@@ -44,7 +82,10 @@ download_tiktok_video () {
         if ! mkdir -v "$DIRECTORY"; then
             exit 1
         fi
-        cd "$DIRECTORY"
+        if ! cd "$DIRECTORY"; then
+            printf 'error: failure changing to directory: %s\n' "$DIRECTORY" >&2
+            exit 1
+        fi
     else
         echo "error: directory '$DIRECTORY' already exists" >&2
         return 128
@@ -52,41 +93,30 @@ download_tiktok_video () {
 
     if [ ! -d "pages" ]; then
         mkdir -v -- "pages" || exit 1
-        cd "pages" || exit 1
-        yt-dlp --newline --verbose --skip-download --write-pages "$1"
-        cd "/media/TikTok/@$UPLOADER/$DIRECTORY" || exit 1
+        mv -nv "$temp_dir/"*".dump" "./pages/"
     fi
 
-    for page in "pages/$ID_"*.dump; do
-        if grep -q image_post_info "$page"; then
-            for format in display_image owner_watermark_image user_watermark_image thumbnail; do
-                jq -r ".aweme_list[0].image_post_info.images[].$format.url_list[1]" "$page" | while read -r url; do
-                    curl --remote-header-name --remote-name --remote-time "$url"
-                done
-            done
-            yt-dlp --newline --verbose --write-description --write-info-json --write-thumbnail --convert-thumbnails png --keep-video --format play_addr --output "%(id)s.%(ext)s" "$1"
-            if [[ "$PWD" = "/media/TikTok/@$UPLOADER/$DIRECTORY" ]]; then
-                touch -t "$(date -d "@$TIMESTAMP" +%Y%m%d%H%M.%S)" ./*photomode*
-                touch -t "$(date -d "@$TIMESTAMP" +%Y%m%d%H%M.%S)" ./"$ID"*
-                touch -t "$(date -d "@$TIMESTAMP" +%Y%m%d%H%M.%S)" .
-            fi
-            return 0
-        fi
-    done
+    "$YT_DLP" --newline --verbose --skip-download --list-thumbnails --list-formats --load-info-json "$temp_info_json"
 
-    yt-dlp --newline --verbose --write-description --write-info-json --write-thumbnail --convert-thumbnails png --output "%(id)s.%(ext)s" "$1"
-    yt-dlp --newline --verbose --format download/download_addr-0/download_addr-1/download_addr-2 --output "%(id)s.watermarked.%(ext)s" "$1"
+    "$YT_DLP" --newline --verbose --write-description --write-info-json --write-thumbnail --convert-thumbnails png --output "%(id)s.%(ext)s" --load-info-json "$temp_info_json"
 
-    #/Users/Richard/yt-dlp-venv/bin/yt-dlp --embed-metadata --embed-thumbnail "$1"
-    #/Users/Richard/yt-dlp-venv/bin/yt-dlp --output "%(id)s.%(ext)s" "$1"
+    "$YT_DLP" --newline --verbose --format download/download_addr-0/download_addr-1/download_addr-2 --output "%(id)s.watermarked.%(ext)s" --load-info-json "$temp_info_json"
 
-    #/Users/Richard/yt-dlp-venv/bin/yt-dlp --embed-metadata --embed-thumbnail --format download_addr-0 --output "%(title)s (watermarked) [%(id)s].%(ext)s" "$1"
-    #/Users/Richard/yt-dlp-venv/bin/yt-dlp --format download_addr-0 --output "%(id)s.watermarked.%(ext)s" "$1"
+    # Display detailed file info before changing timestamps
+    find "$PWD" -exec ls -dlR --full-time --color=never {} +
+    find "$PWD" -exec stat -t {} +
 
-    if [[ "$PWD" = "/media/TikTok/@$UPLOADER/$DIRECTORY" ]]; then
+    if [[ "$PWD" = "/media/$SERVICE/@$UPLOADER/$DIRECTORY" ]]; then
         touch -t "$(date -d @"$TIMESTAMP" +%Y%m%d%H%M.%S)" ./"$ID"*
         touch -t "$(date -d @"$TIMESTAMP" +%Y%m%d%H%M.%S)" .
     fi
+
+    # Display detailed file info after changing timestamps
+    find "$PWD" -exec ls -dlR --full-time --color=never {} +
+    find "$PWD" -exec stat -t {} +
+
+    # Remove temporary directory
+    rm -rv "$temp_dir" || exit 1
 
     return 0
 }
